FROM python:3.11-slim

WORKDIR /backend

# Install system dependencies (needed for livekit and other packages)
RUN apt-get update && apt-get install -y \
    build-essential \
    libglib2.0-0 \
    libgirepository1.0-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy all backend files (app.py, agent.py, etc.)
COPY . .

# Default command (overridden by Compose)





ENV PYTHONPATH=/backend
ENV PATH="/root/.local/bin:$PATH"


CMD ["python","-m", "agent", "dev"]